# go-blockchain task-unit-tests.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: go-blockchain

outputs:
- name: coverage-results

run:
  path: ./go-blockchain/ci/scripts/unit-tests.sh
