# go-blockchain task-build.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: go-blockchain

outputs:
- name: dist

run:
  path: ./go-blockchain/ci/scripts/build.sh
