# go-blockchain pipeline.yml

jobs:

- name: job-unit-tests
  plan:
  - get: go-blockchain
    trigger: true
  - task: task-unit-tests
    file: go-blockchain/ci/tasks/task-unit-tests.yml
    on_success:
      do:
      - put: go-blockchain
        params:
          repository: go-blockchain

- name: job-build
  plan:
    - get: go-blockchain
      trigger: true
      passed: [job-unit-tests]
    - task: task-build
      file: go-blockchain/ci/tasks/task-build.yml
    - put: resource-dump-to-dockerhub
      params: { build: "dist"}

resources:

- name: go-blockchain
  type: git
  source:
    #uri: https://github.com/marioarranzr/go-blockchain
    uri: git@github.com:marioarranzr/go-blockchain.git
    branch: master
    private_key: {{git_private_key}}

- name: resource-dump-to-dockerhub
  type: docker-image
  source:
    repository: marioarranzr/go-blockchain
    tag: latest
    username: marioarranzr
    password: {{dockerhub_password}}
